num_months: !!int 400

market_config_path: !!str "rent_buy_invest/configs/examples/example-1/market-config.yaml"

rent_config_path: !!str "rent_buy_invest/configs/examples/example-1/rent-config.yaml"

buy_config_path: !!str "rent_buy_invest/configs/examples/example-1/buy-config.yaml"

personal_config_path: !!str "rent_buy_invest/configs/examples/example-1/personal-config.yaml"

start_date: !!timestamp "2030-07-01"
