market_rate_of_return: !!float 0.07

tax_brackets_inflation: !!float 0.02

tax_brackets:
  ordinary_income_tax_brackets:
    -
      upper_limit: !!float 44625.
      tax_rate: !!float 0.
    -
      upper_limit: !!float 492300.
      tax_rate: !!float 0.15
    -
      upper_limit: !!float .inf
      tax_rate: !!float 0.2
  long_term_capital_gains_tax_brackets:
    -
      upper_limit: !!float 44625.
      tax_rate: !!float 0.
    -
      upper_limit: !!float 492300.
      tax_rate: !!float 0.10
    -
      upper_limit: !!float .inf
      tax_rate: !!float 0.15
