num_months: !!int 359

market_config_path: !!str "rent_buy_invest/configs/examples/market-config-example-1.yaml"

rent_config_path: !!str "rent_buy_invest/configs/examples/rent-config-example-1.yaml"

house_config_path: !!str "rent_buy_invest/configs/examples/house-config-example-1.yaml"

start_date: !!timestamp "2030-07-01"
