num_months: !!int 40

market_config_path: !!str "rent_buy_invest/core/test_resources/test-market-config.yaml"

rent_config_path: !!str "rent_buy_invest/core/test_resources/test-rent-config.yaml"

buy_config_path: !!str "rent_buy_invest/core/test_resources/test-buy-config.yaml"
