monthly_rent: !!float 2000.0

monthly_utilities: !!float 300.

monthly_renters_insurance: !!float 20.

monthly_parking_fee: null

annual_rent_inflation_rate: !!float 0.03

inflation_adjustment_period: !!int 12
