##### BASICS AND GENERAL CONFIGS

sale_price: !!float 500000.

annual_assessed_value_inflation_rate: !!float 0.05

##### MORTGAGE RELATED CONFIGS

down_payment_fraction: !!float 0.2

mortgage_annual_interest_rate: !!float 0.06

mortgage_term_months: !!int 360

upfront_mortgage_insurance_fraction: !!float 0.0

annual_mortgage_insurance_fraction: !!float 0.005

is_fha_loan: false

mortgage_origination_points_fee_fraction: !!float 0.015

mortgage_processing_fee: !!float 300.

mortgage_underwriting_fee: !!float 500.

mortgage_discount_points_fee_fraction: !!float 0.005

home_appraisal_cost: !!float 500.

credit_report_fee: !!float 50.

##### TAXES

transfer_tax_fraction: !!float 0.0011

seller_burden_of_transfer_tax_fraction: !!float 0.9

recording_fee_fraction: !!float 0.03

annual_property_tax_rate: !!float 0.01

##### MISCELLANEOUS CLOSING COSTS

realtor_commission_fraction: !!float 0.025

hoa_transfer_fee: !!float 300.

seller_burden_of_hoa_transfer_fee: !!float 1.0

home_inspection_cost: !!float 500.

pest_inspection_cost: !!float 500.

escrow_fixed_fee: !!float 500.

flood_certification_fee: !!float 20.

title_search_fee: !!float 100. 

seller_burden_of_title_search_fee_fraction: !!float 1.

attorney_fee: !!float 800.

closing_protection_letter_fee: null

search_abstract_fee: !!float 300.

survey_fee: !!float 500.

notary_fee: !!float 100.

deed_prep_fee: !!float 50.

lenders_title_insurance_fraction: !!float 0.02

owners_title_insurance_fraction: !!float 0.01 

endorsement_fees: !!float 150.

##### MISCELLANEOUS MONTHLY COSTS

annual_homeowners_insurance_fraction: !!float 0.005

monthly_utilities: !!float 300.

annual_maintenance_cost_fraction: !!float 0.02

monthly_hoa_fees: !!float 250.

##### MANAGEMENT COSTS

annual_management_cost_fraction: !!float 0.02
