market_rate_of_return: null

tax_brackets:
  tax_brackets:
    -
      upper_limit: !!float 44625.
      tax_rate: !!float 0.
    -
      upper_limit: !!float 492300.
      tax_rate: !!float 0.15
    -
      upper_limit: !!float .inf
      tax_rate: !!float 0.2
