market_rate_of_return: !!float 0.07

tax_brackets:
  tax_brackets:
    -
      upper_limit: !!float 44625.
      tax_rate: !!float 0.
    -
      upper_limit: !!float 492300.
      tax_rate: !!float 0.15
    -
      upper_limit: !!float .inf
