


##### BASICS AND GENERAL CONFIGS

sale_price: !!float 500000

annual_assessed_value_inflation_rate: !!float 0.05

# NOTE: I don't fully understand prepaid expenses
# NOTE: These configs do not account for prepaid interest, for a few reasons:
# 1) It seems some of the prepaid expenses are just paying things maybe a month
#     or year early (that you would have had to pay later anyways) - this will
#     not significantly affect financial planning, especially if you don't sell
#     the newly bought house within a year
# 2) It seems some of the prepaid expenses (like prepaid mortgage interest) is
#     mainly to "prorate" for the time in between closure and the official start
#     of a monthly billing cycle or something. In this case, you pay this up
#     front, but all future payments are "delayed" so it cancels out. I.e., you
#     can treat it as if there is no interim period, and in fact, the whole
#     point of the prepaid expense is to compensate for any interim period to
#     make it even out anyways!


##### MORTGAGE RELATED CONFIGS

down_payment_fraction: !!float 0.2

mortgage_annual_interest_rate: !!float 0.07

mortgage_term_months: !!int 360

pmi_fraction: !!float 0.005

mortgage_origination_points_fee_fraction: !!float 0.015

mortgage_processing_fee: !!float 300

mortgage_underwriting_fee: !!float 500

mortgage_discount_points_fee_fraction: !!float 0.005

house_appraisal_cost: !!float 500

credit_report_fee: !!float 50

##### TAXES

transfer_tax_fraction: !!float 0.0011

seller_burden_of_transfer_tax_fraction: !!float 0.9

recording_fee_fraction: !!float 0.03

annual_property_tax_rate: !!float 0.01


##### MISCELLANEOUS CLOSING COSTS

realtor_commission_fraction: !!float 0.025

hoa_transfer_fee: !!float 300

seller_burden_of_hoa_transfer_fee: !!float 1.0

house_inspection_cost: !!float 500

pest_inspection_cost: !!float 500

escrow_fixed_fee: !!float 500

flood_certification_fee: !!float 20

title_search_fee: !!float 100 # 

seller_burden_of_title_search_fee_fraction: !!float 1

attorney_fee: !!float 800

closing_protection_letter_fee: !!float 35

search_abstract_fee: !!float 300

survey_fee: !!float 500

notary_fee: !!float 100

deed_prep_fee: !!float 50

lenders_title_insurance_fraction: !!float 0.02

owners_title_insurance_fraction: !!float 0.01 

# TODO not sure if this is for lenders, owners, or both
endorsement_fees: !!float 150


##### MISCELLANEOUS MONTHLY COSTS

annual_homeowners_insurance_fraction: !!float 0.005

monthly_utilities: !!float 300

annual_maintenance_cost_fraction: !!float 0.02

monthly_hoa_fees: !!float 250

##### MANAGEMENT COSTS

# total ANNUAL cost of managing the house without living in it (being a
# landlord) EXCEPT for maintenance costs that you'd expect to pay even if you
# lived in the house. Note that this means if you expect maintenance costs to be
# higher when you do not live in the house vs when you live in it (because you
# think tenants will take worse care of the house than you would if you lived in
# it), that difference in cost should contribute to this parameter. Note this
# parameter can include paying a management company, advertising the house, any
# trips you may have to make, anything associated with managing / landlord
# Expressed as fraction of assessed house price
annual_management_cost_fraction: !!float 0.02
