# Config file relating to assumptions about the market


# ANNUAL rate of return in the market, as a fraction
market_rate_of_return: !!float 0.07

# tax information - assume only capital gains tax
# assume the investor will remain in the market long-term
# therefore, only list long-term capital gains rates
tax_brackets:
  tax_brackets:
    -
      upper_limit: !!float 40000
      tax_rate: !!float 0
    -
      upper_limit: !!float 100000
      tax_rate: !!float 0.15
    -
      upper_limit: !!float .inf
      tax_rate: !!float 0.2
