##### BASICS AND GENERAL CONFIGS

sale_price: !!float 500000.

annual_assessed_value_inflation_rate: !!float 0.07

##### MORTGAGE RELATED CONFIGS

down_payment_fraction: !!float 0.0

mortgage_annual_interest_rate: !!float 0.07

mortgage_term_months: !!int 360

upfront_mortgage_insurance_fraction: !!float 0.0

annual_mortgage_insurance_fraction: !!float 0.005

is_fha_loan: false

mortgage_origination_points_fee_fraction: !!float 0.0

mortgage_processing_fee: !!float 0.0

mortgage_underwriting_fee: !!float 0.0

mortgage_discount_points_fee_fraction: !!float 0.0

home_appraisal_cost: !!float 500

credit_report_fee: !!float 0.0

##### TAXES

transfer_tax_fraction: !!float 0.0

seller_burden_of_transfer_tax_fraction: !!float 1.0

recording_fee_fraction: !!float 0.0

annual_property_tax_rate: !!float 0.01

##### MISCELLANEOUS CLOSING COSTS

buyer_realtor_commission_fraction: !!float 0.0

seller_realtor_commission_fraction: !!float 0.0

hoa_transfer_fee: !!float 0.0

seller_burden_of_hoa_transfer_fee: !!float 1.0

home_inspection_cost: !!float 500.0

pest_inspection_cost: !!float 0.0

escrow_fixed_fee: !!float 0.0

flood_certification_fee: !!float 0.0

title_search_fee: !!float 0.0

seller_burden_of_title_search_fee_fraction: !!float 1.

attorney_fee: !!float 0.0

closing_protection_letter_fee: !!float 0.0

search_abstract_fee: !!float 0.0

survey_fee: !!float 0.0

notary_fee: !!float 0.0

deed_prep_fee: !!float 0.0

lenders_title_insurance_fraction: !!float 0.00

owners_title_insurance_fraction: !!float 0.00

endorsement_fees: !!float 0.0

##### MISCELLANEOUS MONTHLY COSTS

annual_homeowners_insurance_fraction: !!float 0.00035

monthly_utilities: !!float 200.

annual_maintenance_cost_fraction: !!float 0.01

monthly_hoa_fees: !!float 200.0

##### RENTAL INCOME RELATED COSTS

rental_income_config:
  annual_management_cost_fraction: !!float 0.0

  rental_income_waiting_period_months: 24

  monthly_rental_income: 1000

  rental_income_annual_inflation_rate: 0.02

  occupancy_rate: 0.6
