# Config file relating to assumptions about the market

--- !MarketConfig
# annual return on money invested in the market, as a decimal
market_return: !!float 0.07

# tax information - assume only capital gains tax
# assume the investor will remain in the market long-term
# therefore, only list long-term capital gains rates
tax_brackets: !TaxBrackets
  tax_brackets:
    -
      upper_limit: !!float 44625
      tax_rate: !!float 0
    -
      upper_limit: !!float 492300
      tax_rate: !!float 0.15
    -
      upper_limit: !!float .inf
      tax_rate: !!float 0.2
