name: Black linter

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: "23.3.0"
