name: Run isort
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      - uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt"
            version: "5.11.5"
