name: isort import sorter
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      - uses: isort/isort-action@master
        with:
            # requirementsFiles: "requirements.txt"
            requirements-files: "requirements.txt"
            # version: "5.12.0"
            isort-version: "5.12.0"
            profile: "black"
            line-length: 88
      
