name: pytest runner

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
          requirementsFiles: "requirements.txt"
      - name: Install pip
      - run: |
          python -m pip install --upgrade pip
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run pytest
        run: |m
          pytest .
